# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
#Loom
loom_version=1.7-SNAPSHOT
#Modrinth
modrinth_versions=["1.21", "1.21.1"]
#`release`, `beta` or `alpha`
release_channel=release
#
# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.1
loader_version=0.16.0
fabric_version=0.102.0+1.21.1
# Mod Properties
mod_version=21.0.7
maven_group=de.ambertation.wunderlib
archives_base_name=wunderlib
# Dependencies