plugins {
    id 'idea'
    id 'net.fabricmc.fabric-loom'
}
java {
    withSourcesJar()
}
sourceSets {
    main {
        java {
            srcDirs += ['src/client/java', 'src/datagen/java']
        }
    }
}

tasks.sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

apply from: "wunderlib.gradle"